"""empty message

Revision ID: 33546234bad3
Revises: 1589d1b06b8c
Create Date: 2023-05-02 03:47:42.546506

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '33546234bad3'
down_revision = '1589d1b06b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    # ### end Alembic commands ###
