"""trying to delete account model

Revision ID: 62fb0b807136
Revises: 33546234bad3
Create Date: 2023-05-03 15:48:15.498033

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '62fb0b807136'
down_revision = '33546234bad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
